In [46]:
import pandas as pd

pd.set_option('display.max_columns', 50)

df = pd.read_csv('dataset.csv', index_col = [0])
# Drop track_id column as we don't need it in this analysis/machine learning model

df['duration_s'] = df['duration_ms'] *(1/1000) * (1/60)
df = df.drop_duplicates()
# df = df.drop(['track_id', 'duration_ms'], axis=1)

In [47]:
df.shape

(113550, 21)

In [59]:
df[df.duplicated(subset=['track_name', 'time_signature'], keep=False)].sort_values('track_name', ascending=False)

,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre,duration_s
99504,5LiWJsSSjZh7Y3hqml18Ki,Eddy Kim,당신이 잠든 사이에 Pt. 1 Original Television Soundtrack,긴 밤이 오면,56,226991,False,0.480,0.501,5,-5.511,1,0.0296,0.6240,0.000,0.0748,0.2220,110.889,4,singer-songwriter,3.783183
102506,5LiWJsSSjZh7Y3hqml18Ki,Eddy Kim,당신이 잠든 사이에 Pt. 1 Original Television Soundtrack,긴 밤이 오면,56,226991,False,0.480,0.501,5,-5.511,1,0.0296,0.6240,0.000,0.0748,0.2220,110.889,4,songwriter,3.783183
70665,0FBjsiiUFLET2xqeKVrGBE,Eason Chan,我的快樂時代 (華星40系列),黃金時代,46,248040,False,0.555,0.494,4,-6.862,1,0.0285,0.2460,0.000,0.2910,0.2800,144.044,4,mandopop,4.134000
12313,0FBjsiiUFLET2xqeKVrGBE,Eason Chan,我的快樂時代 (華星40系列),黃金時代,46,248040,False,0.555,0.494,4,-6.862,1,0.0285,0.2460,0.000,0.2910,0.2800,144.044,4,cantopop,4.134000
62807,5v1dhqe9vgvp87eyd27hkb,yama,the meaning of life,麻痺,58,198040,False,0.309,0.941,0,-3.558,0,0.0763,0.0587,0.000,0.4350,0.7040,100.020,4,j-pop,3.300667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4152,2Bc4llhjJBW77I552RgA3L,Aphex Twin,Selected Ambient Works Volume II,#3,64,464293,False,0.167,0.071,6,-27.108,0,0.0410,0.9110,0.855,0.1070,0.0613,143.315,5,ambient,7.738217
111315,1Ffxfl1vuEDc0xBVPIQ50s,Kid Koala,"""Was He Slow?"" (Music From The Motion Picture ...","""Was He Slow?"" - Music From The Motion Picture...",37,106880,False,0.754,0.719,10,-5.806,0,0.3710,0.3730,0.259,0.1200,0.6740,175.990,4,trip-hop,1.781333
111402,03XMXPAE2Yx6HeqCpAPL5o,Kid Koala,Baby Driver (Music from the Motion Picture),"""Was He Slow?"" - Music From The Motion Picture...",25,106880,False,0.754,0.719,10,-5.806,0,0.3710,0.3730,0.259,0.1200,0.6740,175.990,4,trip-hop,1.781333
16385,4yfFraZrNnh2zJTok5fzq7,Felix Mendelssohn;Christopher Herrick;Simon Pr...,Klassische Weihnachtsmusik,"""Hark! The Herald Angels Sing""",0,141000,False,0.158,0.210,7,-16.398,1,0.0330,0.9530,0.860,0.1530,0.1930,80.984,4,classical,2.350000
39446,4yfFraZrNnh2zJTok5fzq7,Felix Mendelssohn;Christopher Herrick;Simon Pr...,Klassische Weihnachtsmusik,"""Hark! The Herald Angels Sing""",0,141000,False,0.158,0.210,7,-16.398,1,0.0330,0.9530,0.860,0.1530,0.1930,80.984,4,german,2.350000

In [56]:
df.query('track_name.str.lower() == "run rudolph run"').sort_values('time_signature', ascending=False)['time_signature'].unique()

array([4], dtype=int64)

In [49]:
df.groupby(['track_name', 'time_signature']).agg(bilang = ('track_id', 'count')).sort_values('bilang', ascending=False).reset_index()

                                     track_name  time_signature  bilang
0                               Run Rudolph Run               4     151
1                                     Halloween               4      87
2                            Frosty The Snowman               4      80
3                Little Saint Nick - 1991 Remix               4      74
4                                Christmas Time               4      72
...                                         ...             ...     ...
74638                                  Idea 686               4       1
74639                                   Idealna               4       1
74640                           Ideia de Jerico               4       1
74641  Identidade / Singelo Menestral - Ao Vivo               4       1
74642                                   행복하길 바래               4       1

[74643 rows x 3 columns]

In [8]:
# Data cleaning starts here:

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 114000 entries, 0 to 113999
Data columns (total 19 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   artists           113999 non-null  object
 1   album_name        113999 non-null  object
 2   track_name        113999 non-null  object
 3   popularity        114000 non-null  int64
 4   explicit          114000 non-null  bool
 5   danceability      114000 non-null  float64
 6   energy            114000 non-null  float64
 7   key               114000 non-null  int64
 8   loudness          114000 non-null  float64
 9   mode              114000 non-null  int64
 10  speechiness       114000 non-null  float64
 11  acousticness      114000 non-null  float64
 12  instrumentalness  114000 non-null  float64
 13  liveness          114000 non-null  float64
 14  valence           114000 non-null  float64
 15  tempo             114000 non-null  float64
 16  time_signature    114000 non-null  int64
 17  track_genre       114000 non-null  object
 18  duration_s        114000 non-null  float64
dtypes: bool(1), float64(10), int64(4), object(4)
memory usage: 16.6+ MB